set LINUX_ZBX_REPO_ROOT=/home/mikhail/git/zabbix_agent_win/

set LINUX_MACHINE_USER=mikhail
set LINUX_MACHINE_IP=192.168.56.201
set LINUX_MACHINE_PASSWORD="password"

set WIN_7ZIP_PATH=C:\Program Files\7-Zip\7z.exe
set WIN_VCPKG_ROOT_DIR=C:\git\vcpkg

set WIN_AGENT1_ROOT_DIR=C:\zabbix_agent1
set WIN_AGENT1_TEMP_DIR=%WIN_AGENT1_ROOT_DIR%\tmp
set WIN_AGENT1_LOG_DIR=%WIN_AGENT1_ROOT_DIR%\log
set WIN_AGENT1_CONF_DIR=%WIN_AGENT1_ROOT_DIR%\conf

@REM set WIN_AGENT2_ROOT_DIR=C:\zabbix_agent2
set WIN_AGENT2_ROOT_DIR=%cd%
set WIN_AGENT2_TEMP_DIR=%WIN_AGENT2_ROOT_DIR%\tmp
set WIN_AGENT2_LOG_DIR=%WIN_AGENT2_ROOT_DIR%\log
set WIN_AGENT2_CONF_DIR=%WIN_AGENT2_ROOT_DIR%\conf
