call variables1.bat

@RD /S /Q "%WIN_AGENT_TEMP_DIR%"
mkdir "%WIN_AGENT_TEMP_DIR%"

plink -batch -pw %LINUX_MACHINE_PASSWORD% %LINUX_MACHINE_USER%@%LINUX_MACHINE_IP% cd %LINUX_ZBX_REPO_ROOT%; make dist
pscp -pw %LINUX_MACHINE_PASSWORD% %LINUX_MACHINE_USER%@%LINUX_MACHINE_IP%:%LINUX_ZBX_REPO_ROOT%zabbix*.tar.gz "%WIN_AGENT_TEMP_DIR%"

"%WIN_7ZIP_PATH%" x -y "%WIN_AGENT_TEMP_DIR%\zabbix*.tar.gz" -o"%WIN_AGENT_TEMP_DIR%"
"%WIN_7ZIP_PATH%" x -y "%WIN_AGENT_TEMP_DIR%\zabbix*.tar" -o"%WIN_AGENT_TEMP_DIR%"
